replicaCount: 1

image:
  repository: cybershield
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: cybershield.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  FLASK_ENV: production
  DEBUG: "False"
  PORT: "5000"
  DATABASE_URL: sqlite:////app/instance/cybershield.db

secretEnv:
  JWT_SECRET_KEY: change-this-in-production

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
