apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cybershield.fullname" . }}
  labels:
    {{- include "cybershield.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cybershield.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cybershield.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: FLASK_ENV
              value: "{{ .Values.env.flaskEnv }}"
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: DATABASE_URL
              value: "{{ .Values.env.databaseUrl }}"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "cybershield.secretName" . }}
                  key: jwtSecretKey
            - name: CORS_ORIGINS
              value: "{{ .Values.env.corsOrigins }}"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | nindent 12 }}
