apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cybershield.secretName" . }}
  labels:
    {{- include "cybershield.labels" . | nindent 4 }}
type: Opaque
data:
  jwtSecretKey: {{ .Values.jwtSecretKey | b64enc }}
